### ISSUE TITLE
brute force option seems not working

### ISSUE THREAD

**Issue by freetom** [hyc/fcrackzip#1]
I've created a zipped test file with "aaa" as password but when I try to run:
fcrackzip -b -l 3-3 xxx.zip  | grep "aaa"
I have no output. why?

Using a debian linux system. fcrackzip version 1.0

thanks

**Comment by WeihuaGu** [comment]
first you shoud test the unzip commman. in some file , in my computer ,unzip filename maybe return 'skipping: XXX           need PK compat. v5.1 (can do v4.6)'
if the unzip can not work ,the fcrackzip not work……

**Comment by freetom** [comment]
I just zip a C source file, when promped for the password I put "aaa", then try to crack it:
```shell
zip -re a.zip a.c
fcrackzip -b -l 3-3 a.zip
```
The output of fcrackzip says that he found a ton of possible passwords and nothing more..
 
```
...
possible pw found: )74 ()
possible pw found: )!d ()
possible pw found: )%V ()
possible pw found: )?C ()
possible pw found: ){p ()
possible pw found: )+e ()
possible pw found: =eF ()
possible pw found: =hb ()
possible pw found: =iV ()
possible pw found: =o0 ()
possible pw found: =p5 ()
...
```
I tried also different methods with the `-m` instruction. What's wrong?

**Comment by hyc** [comment]
What do you mean, what's wrong? What did you expect it to output?

I did the same as you:
```
violino:/home/software/fcrackzip-1.0> zip -re a.zip crack.h
Enter password: 
Verify password: 
  adding: crack.h (deflated 50%)
violino:/home/software/fcrackzip-1.0> ./fcrackzip  -b -l 3-3 a.zip
possible pw found: aaa ()
possible pw found: ai= ()
possible pw found: akq ()
possible pw found: anN ()
possible pw found: an= ()
possible pw found: apO ()
possible pw found: arg ()
...
```

Looks like it worked fine to me.

**Comment by WeihuaGu** [comment]
I tested again
```
better@better:~/tmp$ fcrackzip -b -l 3-3 a.zip
possible pw found: aaa ()
possible pw found: afg ()
possible pw found: ah* ()
possible pw found: aiN ()
possible pw found: am5 ()
possible pw found: ap* ()
possible pw found: aqg ()
```
the output same with hyc's test.
may  add the -c  a1!

**Comment by WeihuaGu** [comment]
But when i make a zip named test.zip with passwd 2317
then 
`fcrackzip -b -l 4 -c 1 test.zip | cut -d ' ' -f 4 | grep 2317`
the output was null.
the possible password not include 2317.

**Comment by DaWe35** [comment]
Same here, I tried to crack my brake.zip (password: asd), and not successed.
`fcrackzip -b -l 1-4 -u zcr.zip`
[break-aes256.zip](https://github.com/hyc/fcrackzip/files/3689999/break-aes256.zip)
[break-zipCrypto.zip](https://github.com/hyc/fcrackzip/files/3690000/break-zipCrypto.zip)
(zipped with 7zip, windows 10, and encoded with AES-256 and ZipCrypto.)

**Comment by hyc** [comment]
For your break-aes256.zip file, I get "unknown compression method" so libunzip can't read your file at all.

For your break-zipCrypto.zip, I got:
````
./fcrackzip -b -l 1-4 -u /tmp/break-zipCrypto.zip 


PASSWORD FOUND!!!!: pw == N
````

And indeed, using this as the password works. Since you only encrypted a zero-length file, I'm sure there are plenty of passwords that would work for it. You need to use a file with at least some actual data in it, to properly test.

**Comment by ghost** [comment]
> I just zip a C source file, when promped for the password I put "aaa", then try to crack it:
> 
> ```shell
> zip -re a.zip a.c
> fcrackzip -b -l 3-3 a.zip
> ```
> 
> The output of fcrackzip says that he found a ton of possible passwords and nothing more..
> 
> ```
> ...
> possible pw found: )74 ()
> possible pw found: )!d ()
> possible pw found: )%V ()
> possible pw found: )?C ()
> possible pw found: ){p ()
> possible pw found: )+e ()
> possible pw found: =eF ()
> possible pw found: =hb ()
> possible pw found: =iV ()
> possible pw found: =o0 ()
> possible pw found: =p5 ()
> ...
> ```
> 
> I tried also different methods with the `-m` instruction. What's wrong?

-u, --use-unzip Try to decompress the first file by calling unzip with the guessed password. This weeds out false positives when not enough files have been given.
