### ISSUE TITLE
Stop the proccess with no result

### ISSUE THREAD

**Issue by hybridln** [hyc/fcrackzip#10]
i am trying to find a zip password , i know that the password contains only numbers 
and i am giving 
`fcrackzip -b -c 1 -p 1111111111  file.zip`

everytime the proccess finishes with no result(no message, etc)

`unzip file.zip 
Archive:  file.zip
 unsupported compression method 99
`

**Comment by hyc** [comment]
No result because your file uses an unsupported compression method.
