### ISSUE TITLE
Error: 8 file maximum reached, skipping further files

### ISSUE THREAD

**Issue by Sha4p3y3** [hyc/fcrackzip#13]
Trying to crack a zip file that has multiple folders and files in it. Is this a limitation of fcrackzip or am I doing something wrong?

# fcrackzip -u -D -v -p password.txt ./zipfile.zip
'folder/' is not encrypted, skipping
'folder/folder/' is not encrypted, skipping
'folder/folder/projects/' is not encrypted, skipping
'folder/folder/projects/00/' is not encrypted, skipping
found file 'folder/folder/projects/00/file.txt', (size cp/uc    199/   262, flags 1, chk 0000)
folder/folder/projects/01/' is not encrypted, skipping
found file 'filename.cmp', (size cp/uc     66/   135, flags 1, chk 0000)
found file 'filename.hdl', (size cp/uc    267/   342, flags 1, chk 0000)
found file 'filename.tst', (size cp/uc    256/   426, flags 1, chk 0000)
found file 'filename.cmp', (size cp/uc    115/   420, flags 1, chk 0000)
found file 'filename', (size cp/uc    284/   352, flags 1, chk 0000)
found file 'filename.tst', (size cp/uc    302/   715, flags 1, chk 0000)
found file 'filename.cmp', (size cp/uc     74/   175, flags 1, chk 0000)
8 file maximum reached, skipping further files

**Comment by hyc** [comment]
This is the MAX_FILES limit defined in crack.h. Change it if you want a larger value.

**Comment by bastetfurry** [comment]
So the tool is useless when installed from a repository, we need to compile it ourselves. Would have loved to know that beforehand. :)

**Comment by hyc** [comment]
I have never provided binaries for this code. It has always required you to compile it yourself. If you're running from someone's repo, complain to them, not me.
