### ISSUE TITLE
Featurerequest: Other Compression Formats?

### ISSUE THREAD

**Issue by vyrsh** [hyc/fcrackzip#15]
I found your program and it really suits my needs... the Number of options is remarkable and i doubt even Paid applications could level this.... But I found out **7z** doesn't work with the cracker(does it?)... **BIG THANKYOU** if you could add that feature if it isn't taking too much time or isn't too complex.... Thankyou

**Comment by hyc** [comment]
As I state in the README this program is obsolete, the feature you want is already in John the Ripper.
https://github.com/openwall/john
