### ISSUE TITLE
fcrackzip in windows 10 No such file or directory

### ISSUE THREAD

**Issue by ee406621** [hyc/fcrackzip#16]
**fcrackzip -b -c -d d:\ '1' -u D:\Disktop\Downloads\test.zip**
skipping 'D:DisktopDownloadstest.zip': No such file or directory
no usable files found

Other way
**fcrackzip -b -c '1' -u test.zip**
skipping 'test.zip': No such file or directory
no usable files found

other
 fcrackzip -D -p D:\Disktop\Downloads\Compressedrockyou.text -u D:\Disktop\Downloads\Compressed\t
est.zip
skipping 'D:DisktopDownloadsCompressedtest.zip': No such file or directory
no usable files found

fcrackzip -D -p D:\Disktop\Downloads\Compressedrockyou.text -u D:/Disktop/Downloads/Compressed/t
est.zip
skipping 'D:/Disktop/Downloads/Compressed/test.zip': No such file or directory
no usable files found

**Comment by tijldeneut** [comment]
Works here, but on Windows it fails the use the libzip library for automatic unzip testing (the "-u" parameter). 
But without that parameter, it seems to work.
