### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by AtomicNess123** [hyc/fcrackzip#18]
How to compile or install this? Thanks.

**Comment by karanS08** [comment]
sudo apt install fcrackzip

**Comment by AtomicNess123** [comment]
Closed too soon :) I get this:

`Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/apt`

**Comment by brokercl** [comment]
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/apt" (-1)
