### ISSUE TITLE
Where to find the libunzip

### ISSUE THREAD

**Issue by jcbastosportela** [hyc/fcrackzip#2]
Hi, I'm trying to modify this code in order to delete most of the stdout prints for decreasing CPU load, but I can't find the libunzip (with unzip.h).

Can you help?

**Comment by hyc** [comment]
There are Ubuntu packages for it, but you can get the original source here http://www.info-zip.org/UnZip.html

**Comment by jcbastosportela** [comment]
@hyc thanks for replying.
I use Mint and I couldn't find any lib-dev for it. Going to try the source.

Thanks!
