### ISSUE TITLE
fatal error: unzip.h: No such file or directory

### ISSUE THREAD

**Issue by davidhcefx** [hyc/fcrackzip#5]
$ make
make  all-am
make[1]: Entering directory '/home/davidhcefx/fcrackzip-master'
if gcc -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -funroll-all-loops -O3 -MT main.o -MD -MP -MF ".deps/main.Tpo" \
  -c -o main.o `test -f 'main.c' || echo './'`main.c; \
then mv -f ".deps/main.Tpo" ".deps/main.Po"; \
else rm -f ".deps/main.Tpo"; exit 1; \
fi
**main.c:29:19: fatal error: unzip.h: No such file or directory**
 #include <unzip.h>
                   ^
compilation terminated.
Makefile:269: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
make[1]: Leaving directory '/home/davidhcefx/fcrackzip-master'
Makefile:173: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hyc** [comment]
Learn to read. https://github.com/hyc/fcrackzip/blob/master/README
