### ISSUE TITLE
Security: Special characters in dictionary passed unescaped to shell for unzip-call

### ISSUE THREAD

**Issue by tueksta** [hyc/fcrackzip#6]
As described in https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/ the code in https://github.com/hyc/fcrackzip/blob/master/main.c#L62 is a bit too optimistic about the quality of the dictionary passwords. By having a malicious password in the dictionary file a user executing fcrackzip might execute unwanted commands in his shell.

This is a realistic scenario as dictionary files are loaded from the internet without checking, and it might be a legitimate password but also a danger to anyone trying to crack any zip-file with fcrackzip. There are two roads to solve dictionary passwords with potentially dangerous characters for unzipping: 
* Skip the unzip
* Properly escape the password

**Comment by hyc** [comment]
This report is invalid. The code calls libunzip directly and never invokes any shell.

**Comment by tueksta** [comment]
```
sh: -c: line 0: syntax error near unexpected token `)'
sh: -c: line 0: `unzip -qqtP ""$!)TrEaaSa" fsociety.zip >/dev/null 2>&1'
```

"sh -c spawns a non-login, non-interactive session of sh"

**Comment by hyc** [comment]
You're a moron. Read the code before wasting someone's time like this. The original version of fcrackzip spawns unzip. My version in this repo does not. Whatever you're running to produce the above output is *NOT* this version of the code.

**Comment by tueksta** [comment]
My mistake, didn't see your last commit. Although it would've been helpful to rename the project, I thought I had the original version.

**Comment by hyc** [comment]
Thank you for wasting my time with your carelessness.
